#ifndef PACMANSFML_COLLECTIBLETYPE_H
#define PACMANSFML_COLLECTIBLETYPE_H

enum CollectibleType
{
  POWER_PELLET,
  NORMAL_PELLET,
  CHERRY,
  ORANGE,
  MELON
};

#endif // PACMANSFML_COLLECTIBLETYPE_H
